title: "CSCT-NAIL (CSCT Neuro AI Lab)"
description: "Intelligence within Bounds: Why Cognition Requires a Closed Convex Hull"
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true